#!/usr/local/bin/python3
import os,sys
import vacode_train

if __name__ == '__main__':
    try:
        pid = os.fork()
        if pid > 0:
            print ("fork pid %d" % pid)
            os._exit(0)
    except (OSError,error):
        print ("fork fail: %d %s" % (error.errno, error.strerror))
        os._exit(1)
    sys.stderr.flush()
    sys.stdout.flush()
    logfile = "log"
    if not os.path.isfile(logfile):
        fp = open(logfile, "w")
        fp.close()
    si = open(logfile, "r")
    so = open(logfile, "a+")
    se = open(logfile, "a+")
    os.dup2(si.fileno(), sys.stdin.fileno())
    os.dup2(so.fileno(), sys.stdout.fileno())
    os.dup2(se.fileno(), sys.stderr.fileno())
    vacode_train.main()
